<html>
    <body class="page">
        <div id="score" style="font-size: 24px; padding: 10px;">Puntos: 0</div>
        <div class="game-container">
            <!-- 4*4 -->
             <?php
                shuffle($cartas);   
                for ($i = 0; $i < sizeof($cartas); $i++): ?>
                   <div class="card" data-value="<?= $cartas[$i] ?>">
                        <div class="card-inner">
                            <div class="card-front"></div>
                            <div class="card-back"><?= $cartas[$i] ?></div>
                        </div>
                    </div>
                <?php endfor; ?>
        </div>
        <script src="game.js"></script>
    </body>
</html>
<style>
.page {  
    background-color: aquamarine;
}

.game-container {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
    padding: 20px;
    background-color: rgb(0, 136, 255);
}

.card {
    width: 100px;
    height: 100px;
    perspective: 1000px;
}

.card-inner {
    width: 100%;
    height: 100%;
    position: relative;
    transform-style: preserve-3d;
    transition: transform 0.6s;
}

.card.flip .card-inner {
    transform: rotateY(180deg);
}

.card-front, .card-back {
    position: absolute;
    width: 100%;
    height: 100%;
    backface-visibility: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 24px;
    border: solid 2px black;
    border-radius: 8px;
}

.card-front {
    background: rgb(255, 9, 99);
}

.card-back {
    background: white;
    transform: rotateY(180deg);
}


</style>